---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - files:
        - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
        - "{{ansible_distribution}}.yml"
        - "{{ansible_os_family}}.yml"
      skip: true

- name: create go path
  become: '{{go_escalate}}'
  become_user: root
  with_items:
    - '{{go_path}}'
    - '{{go_profile_dir}}'
  file: >-
    path={{item}}
    state=directory
    mode=0755
      
- name: install go pkgs
  become: '{{go_escalate}}'
  become_user: root
  with_items:
    - '{{go_get|default([])}}'
    - github.com/tools/godep
  command: '{{go_root}}/bin/go get {{item}}'
  environment:
    GOROOT: '{{go_root}}'
    GOPATH: '{{go_path}}'
  args:
    creates: '{{go_path}}/src/{{item}}'

    
- name: set go-dev environment variables
  become: '{{go_escalate}}'
  become_user: root
  with_items:
    - go-dev.sh
  template: >
    src={{item}}.j2
    dest={{go_profile_dir}}/{{item}}
    mode=0644
